<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Derek Taylor">
<meta name="dcterms.date" content="2025-09-30">

<title>Do Higher Reception Yards and Higher Targets mean higher Fantasy Points – My Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0b37c64f34216b628666a8dac638b53b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Do Higher Reception Yards and Higher Targets mean higher Fantasy Points</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">fantasy football</div>
                <div class="quarto-category">Statistical</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Derek Taylor </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 30, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-loadLibraries" id="toc-sec-loadLibraries" class="nav-link active" data-scroll-target="#sec-loadLibraries"><span class="header-section-number">0.1</span> Load Libraries</a></li>
  <li><a href="#sec-aiDisclosure" id="toc-sec-aiDisclosure" class="nav-link" data-scroll-target="#sec-aiDisclosure"><span class="header-section-number">1</span> AI Disclosure</a></li>
  <li><a href="#sec-abstract" id="toc-sec-abstract" class="nav-link" data-scroll-target="#sec-abstract"><span class="header-section-number">2</span> Abstract</a></li>
  <li><a href="#sec-background" id="toc-sec-background" class="nav-link" data-scroll-target="#sec-background"><span class="header-section-number">3</span> Background</a>
  <ul class="collapse">
  <li><a href="#sec-TheResearch" id="toc-sec-TheResearch" class="nav-link" data-scroll-target="#sec-TheResearch"><span class="header-section-number">3.1</span> The Research</a></li>
  </ul></li>
  <li><a href="#sec-method" id="toc-sec-method" class="nav-link" data-scroll-target="#sec-method"><span class="header-section-number">4</span> Method</a></li>
  <li><a href="#sec-data" id="toc-sec-data" class="nav-link" data-scroll-target="#sec-data"><span class="header-section-number">5</span> Data</a>
  <ul class="collapse">
  <li><a href="#wr-tests" id="toc-wr-tests" class="nav-link" data-scroll-target="#wr-tests"><span class="header-section-number">5.1</span> WR Tests</a></li>
  <li><a href="#rb-tests" id="toc-rb-tests" class="nav-link" data-scroll-target="#rb-tests"><span class="header-section-number">5.2</span> RB Tests</a></li>
  <li><a href="#te-tests" id="toc-te-tests" class="nav-link" data-scroll-target="#te-tests"><span class="header-section-number">5.3</span> TE Tests</a></li>
  <li><a href="#test-between-reicieving-yards-and-targets" id="toc-test-between-reicieving-yards-and-targets" class="nav-link" data-scroll-target="#test-between-reicieving-yards-and-targets"><span class="header-section-number">5.4</span> Test Between Reicieving Yards and Targets</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results"><span class="header-section-number">6</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-WrResults" id="toc-sec-WrResults" class="nav-link" data-scroll-target="#sec-WrResults"><span class="header-section-number">6.1</span> WR Results</a></li>
  <li><a href="#rb-results" id="toc-rb-results" class="nav-link" data-scroll-target="#rb-results"><span class="header-section-number">6.2</span> RB Results</a></li>
  <li><a href="#te-results" id="toc-te-results" class="nav-link" data-scroll-target="#te-results"><span class="header-section-number">6.3</span> TE Results</a></li>
  </ul></li>
  <li><a href="#sec-discussion" id="toc-sec-discussion" class="nav-link" data-scroll-target="#sec-discussion"><span class="header-section-number">7</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#sec-strengthsLimitations" id="toc-sec-strengthsLimitations" class="nav-link" data-scroll-target="#sec-strengthsLimitations"><span class="header-section-number">7.1</span> Strengths and Limitations</a></li>
  <li><a href="#sec-conclusion" id="toc-sec-conclusion" class="nav-link" data-scroll-target="#sec-conclusion"><span class="header-section-number">7.2</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#sec-references" id="toc-sec-references" class="nav-link" data-scroll-target="#sec-references"><span class="header-section-number">8</span> References</a></li>
  <li><a href="#sec-sessionInfo" id="toc-sec-sessionInfo" class="nav-link" data-scroll-target="#sec-sessionInfo"><span class="header-section-number">9</span> Session Info</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="sec-loadLibraries" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="sec-loadLibraries"><span class="header-section-number">0.1</span> Load Libraries</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lme4"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"lmerTest"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"effectsize"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"MuMIn"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"emmeans"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjstats"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mgcv"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"AICcmodavg"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"bbmle"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"rstan"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"brms"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"cmdstanr"</span>) <span class="co"># todo: install.packages("cmdstanr", repos = c("https://stan-dev.r-universe.dev", getOption("repos"))); cmdstanr::check_cmdstan_toolchain(); cmdstanr::install_cmdstan()</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"fitdistrplus"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"performance"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"parallelly"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"broom.mixed"</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidybayes"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"plotly"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"viridis"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"../../data/player_stats_weekly.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="sec-aiDisclosure" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> AI Disclosure</h1>
<p>AI Disclosure: AI was not used.</p>
<p>Link to AI Transcript: not applicable</p>
</section>
<section id="sec-abstract" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Abstract</h1>
<p><strong>Background:</strong> When determining what role a player plays on their team you have to look at a series of different stats but a some of the bigger stats to look at are reception yards and target, and they both happen to be good for looking at fantasy points. <strong>Method:</strong> I did a series of correlation test to see how well of a correlation fantasy point had to reception yards and targets. I also broke up the test by the positions WR, TE, and RB. <strong>Results:</strong> I found out the correlations vary per position, WR is as expected very strong correlation between reception yards and fantasy points but moderate when it comes to targets. TE slightly above moderate when it comes to targets correlation with fantasy points but not as strong as the WR when it come to reception yards. RB had a moderate correlation when it came to both targets and reception yards. <strong>Discussion:</strong> Therefore in order to get a full idea of what leads to more fantasy points it’ll be better to dive into one position specifically instead of an over view. But either way the results give a good starting point and idea of what to expect.</p>
</section>
<section id="sec-background" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Background</h1>
<p>When you think of football and skill positions what is one thing you think about. There is a great chance you think about catching the ball. When the NFL breaks down the stats of a football player there are a multitude of stats that focus solely on getting the ball and catching it. Today we will be looking at two of those stats, reception yards and targets. Reception yards is the put together total of yards at time of reception, so how many yards the ball went before being caught, and yards after catch, how many yards the player went with the ball after catching it. Targets is simply how many times the quarterback threw or handed off the football to the intended player. Why is looking at these stats important? It is important to look at these stats because it gives us an idea of how the player performs on the team and what role they play on the team. “Certain players fill a high-risk high-reward role, putting up 15+ yards per reception but not catching those passes at a high rate. Elite receivers do not always put up the most yards per reception, but their high catch percentage and usage leads them to be the most valuable players.” (Bond, 2022) Stats like reception yards and targets help us figure out who are big time player or the consistent reliable player, especially if you are a fantasy football player. In fantasy football stats such as reception yards and targets are some of the best ways to figure out if you should keep the player or cut them, it also give you in idea of how many fantasy points that play could bring in week to week.</p>
<section id="sec-TheResearch" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-TheResearch"><span class="header-section-number">3.1</span> The Research</h2>
<p>The question I will be testing today is, does reception yards and targets correlate with more fantasy points? The reason I am looking into this is because I wonder if players that are more consistent make up most of the fantasy points or is the players that don’t get a lot of catch but make big plays get the most fantasy points. I hypothesize that the players with more consistent yards and targets will make up the most when it comes to fantasy points. I believe this because as someone who has played fantasy football it’s usually the big play players that don’t do well on average and tend to only have a big game every other week.</p>
</section>
</section>
<section id="sec-method" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Method</h1>
<p>I will be running a series of tests looking at the correlation between reception yards and targets with different skill positions: WR, TE, and RB</p>
</section>
<section id="sec-data" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Data</h1>
<p>First, after loading my data, look at the top for reminder, I made a subset of my data to include only WR, RB, and TE.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>player_stats_seasonal_offense_subset <span class="ot">&lt;-</span> player_stats_weekly <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(position_group <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"RB"</span>,<span class="st">"WR"</span>,<span class="st">"TE"</span>) <span class="sc">|</span> position <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"K"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>player_stats_seasonal_offense_subset<span class="sc">$</span>position[<span class="fu">which</span>(player_stats_seasonal_offense_subset<span class="sc">$</span>position <span class="sc">==</span> <span class="st">"HB"</span>)] <span class="ot">&lt;-</span> <span class="st">"RB"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>player_stats_seasonal_offense_subset<span class="sc">$</span>player_idFactor <span class="ot">&lt;-</span> <span class="fu">factor</span>(player_stats_seasonal_offense_subset<span class="sc">$</span>player_id)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>player_stats_seasonal_offense_subset<span class="sc">$</span>positionFactor <span class="ot">&lt;-</span> <span class="fu">factor</span>(player_stats_seasonal_offense_subset<span class="sc">$</span>position)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="wr-tests" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="wr-tests"><span class="header-section-number">5.1</span> WR Tests</h2>
<p>Next I start running my correlation test starting with WR and the correlation between targets and fantasy points</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> targets <span class="sc">+</span> fantasyPoints,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"WR"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  targets and fantasyPoints
t = 180.57, df = 56350, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6001583 0.6106190
sample estimates:
      cor 
0.6054148 </code></pre>
</div>
</div>
<p>Then I did the same test but between receiving yards and fantasy points with WR.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> receiving_yards <span class="sc">+</span> fantasyPoints,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"WR"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  receiving_yards and fantasyPoints
t = 571.18, df = 56350, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.9222014 0.9246336
sample estimates:
      cor 
0.9234268 </code></pre>
</div>
</div>
</section>
<section id="rb-tests" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="rb-tests"><span class="header-section-number">5.2</span> RB Tests</h2>
<p>I then repeated these steps for RB and TE. Starting with RB: Targets - Fantasy Points</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> targets <span class="sc">+</span> fantasyPoints,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"RB"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  targets and fantasyPoints
t = 111.12, df = 37816, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4885033 0.5036992
sample estimates:
      cor 
0.4961392 </code></pre>
</div>
</div>
<p>RB: Receiving Yards - Fantasy Points</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> receiving_yards <span class="sc">+</span> fantasyPoints,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"RB"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  receiving_yards and fantasyPoints
t = 159.28, df = 37816, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6275896 0.6396537
sample estimates:
      cor 
0.6336602 </code></pre>
</div>
</div>
</section>
<section id="te-tests" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="te-tests"><span class="header-section-number">5.3</span> TE Tests</h2>
<p>TE: Targets - Fantasy Points</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> targets <span class="sc">+</span> fantasyPoints,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"TE"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  targets and fantasyPoints
t = 136.82, df = 27436, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6297750 0.6438424
sample estimates:
      cor 
0.6368617 </code></pre>
</div>
</div>
<p>TE: Receiving Yards - Fantasy Points</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> receiving_yards <span class="sc">+</span> fantasyPoints,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"TE"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  receiving_yards and fantasyPoints
t = 307.63, df = 27436, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.8777974 0.8831166
sample estimates:
      cor 
0.8804847 </code></pre>
</div>
</div>
</section>
<section id="test-between-reicieving-yards-and-targets" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="test-between-reicieving-yards-and-targets"><span class="header-section-number">5.4</span> Test Between Reicieving Yards and Targets</h2>
<p>I also ran a correlation test between receiving yards and targets so we can see how the 2 stats compare with each other.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> receiving_yards <span class="sc">+</span> targets,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  receiving_yards and targets
t = 339.64, df = 141839, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6668311 0.6725712
sample estimates:
      cor 
0.6697112 </code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> player_stats_seasonal_offense_subset <span class="sc">%&gt;%</span> <span class="fu">filter</span>(position <span class="sc">==</span> <span class="st">"WR"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> receiving_yards,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> fantasyPoints</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span> ) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"gam"</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Receiving Yards"</span>,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Fantasy Points"</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Correlation Between Fanstasy Points and Receiving Yards"</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ s(x, bs = "cs")'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-results" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Results</h1>
<p>We will break the results down by position</p>
<section id="sec-WrResults" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-WrResults"><span class="header-section-number">6.1</span> WR Results</h2>
<p>Looking at the results of the correlation tests for the WR shows results that might be expected. Starting with the correlation between targets and fantasy points resulting in a 0.6054148 meaning there is a positive moderate correlation. We can interpret this result by thinking about it this way, just because the WR is being targeted doesn’t mean they will get a lot of fantasy points. Clearly the more targets a player gets the more chance for then to get fantasy points leading to that moderate correlation. Looking at the reception yards to fantasy points is a whole other story, there is a very strong positive correlation of 0.9234268. This makes sense when it comes to fantasy points because a bulk of WR points are based off of how many yards they get from catching and running after the catch with the ball. Leading to a very strong correlation. Looking at the difference between the 2 different correlations we can interpret that as not every player with a lot of reception yards has a lot of targets. Suggesting that a portion of the points from reception yards are due to the big play players.</p>
</section>
<section id="rb-results" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="rb-results"><span class="header-section-number">6.2</span> RB Results</h2>
<p>The RB results surprised me both scored a lower correlation than I expected. The test between targets and fantasy points had a slightly moderate positive correlation of 0.4961392, and the test between reception yards and fantasy point is a moderate positive correlation of 0.6336602. This leads me with the question, why did the results come out this way? In honesty with the type of tests I did I can’t tell you what factor is causing them to have a lower correlation than with the WR because in my mind WR and RB go hand in hand when it comes to fantasy points, there like one of the same. I have 2 theories, one is because RB are duel threats meaning they can run the ball on the ground or be receivers, and two they are one of the few positions that lose points a lot due to losing yardage due to a play. Why do these theories matter to the test results because of the data I used to produce the tests a lot of RB gain most yardage on the ground so there isn’t a lot of big numbers receiving yards that would relate to a lot of fantasy points; and since the RB position can be prone to losing yardage therefore getting negative points means that there will be games that they barely score any points leading to the low correlation between targets and fantasy points because they can lose points depending on the play.</p>
</section>
<section id="te-results" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="te-results"><span class="header-section-number">6.3</span> TE Results</h2>
<p>The TE position makes sense with how the results came up, kind of middle of the pact. The TE on the test between targets and fantasy points had a moderately positive correlation of 0.6368617, and on the test between reception yards and fantasy points had a strong correlation of 0.8804847. The TE correlation with targets lines up with the WR because like the WR, TE make there points through catching the ball. The biggest thing to take away from the TE results is the correlation between reception yards and fantasy points and unlike the WR the TE’s correlation isn’t as strong. This is probably due to the fact most TE are used for short, “easy” passes to get some guaranteed yardage instead of a go long. So, the TE is more dependent on getting a touchdown to get there points unlike the WR who can get a lot of points by simply getting a lot of yards.</p>
</section>
</section>
<section id="sec-discussion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Discussion</h1>
<p>Targets and reception yards are big stats that let us determine what role a player may play on their team. The WR have a very strong correlation between reception yards and fantasy points telling us that WR’s score a lot of points simply by catching the ball. But since they had only a moderate target rate it shows that big play players make up a good portion of the reception yard points. Looking back at my hypothesis I was trying to discover if the more reception yards and more targets means that a player will get a lot of fantasy points and now looking at the data it shows that that hypothesis is only partially true. It’s mostly true with WR but it isn’t fully true for TE and it definitely isn’t true RB. I still feel that these tests are a good representation of the data and answered the questions I was seeking to find. I did this test again I would probably focus more deeply on a singular position then just a simple overview.</p>
<section id="sec-strengthsLimitations" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-strengthsLimitations"><span class="header-section-number">7.1</span> Strengths and Limitations</h2>
<p>I believe that the biggest strength of my tests is that they were straight to the point and answered what I sought out to achieve. For limitations it would be helpful if I included a visual so that it would be easier to interpret the data, and the fact that I didn’t test for any outside effects meaning I don’t know the true reasons why some correlations are less than others outside of speculation.</p>
</section>
<section id="sec-conclusion" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-conclusion"><span class="header-section-number">7.2</span> Conclusion</h2>
<p>There you have it, in this study we went through multiple positions to see if there was a correlation between more reception yards and more targets leading to bigger fantasy scores. We came up with that it varies from position to position, leading for us to have to dig a little deeper for determining whether to keep or cut players or to predict when there next big game might be. But for a starter point these stats are a bad place to start.</p>
</section>
</section>
<section id="sec-references" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> References</h1>
<p>Analytics, D. S. (2022, April 18). Yards per reception and its role in wide receiver evaluation. Dartmouth Sports Analytics. https://sites.dartmouth.edu/sportsanalytics/2022/04/21/yards-per-reception-and-its-role-in-wide-receiver-evaluation/</p>
</section>
<section id="sec-sessionInfo" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Session Info</h1>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.2 (2025-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] lubridate_1.9.4     forcats_1.0.1       stringr_1.6.0      
 [4] dplyr_1.1.4         purrr_1.2.0         readr_2.1.6        
 [7] tidyr_1.3.1         tibble_3.3.0        tidyverse_2.0.0    
[10] viridis_0.6.5       viridisLite_0.4.2   plotly_4.11.0      
[13] ggplot2_4.0.1       tidybayes_3.0.7     broom.mixed_0.2.9.6
[16] parallelly_1.45.1   performance_0.15.3  fitdistrplus_1.2-4 
[19] survival_3.8-3      MASS_7.3-65         cmdstanr_0.9.0.9000
[22] brms_2.23.0         Rcpp_1.1.0          rstan_2.32.7       
[25] StanHeaders_2.32.10 bbmle_1.0.25.1      AICcmodavg_2.3-4   
[28] mgcv_1.9-3          nlme_3.1-168        sjstats_0.19.1     
[31] emmeans_2.0.0       MuMIn_1.48.11       effectsize_1.0.1   
[34] lmerTest_3.1-3      lme4_1.1-38         Matrix_1.7-4       

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-3    tensorA_0.36.2.1      jsonlite_2.0.0       
 [4] datawizard_1.3.0      magrittr_2.0.4        TH.data_1.1-5        
 [7] estimability_1.5.1    farver_2.1.2          nloptr_2.2.1         
[10] rmarkdown_2.30        vctrs_0.6.5           minqa_1.2.8          
[13] htmltools_0.5.9       distributional_0.5.0  curl_7.0.0           
[16] broom_1.0.11          unmarked_1.5.1        htmlwidgets_1.6.4    
[19] sandwich_3.1-1        zoo_1.8-14            lifecycle_1.0.4      
[22] pkgconfig_2.0.3       R6_2.6.1              fastmap_1.2.0        
[25] rbibutils_2.4         future_1.68.0         digest_0.6.39        
[28] numDeriv_2016.8-1.1   furrr_0.3.1           ps_1.9.1             
[31] labeling_0.4.3        timechange_0.3.0      httr_1.4.7           
[34] abind_1.4-8           compiler_4.5.2        withr_3.0.2          
[37] S7_0.2.1              backports_1.5.0       inline_0.3.21        
[40] QuickJSR_1.8.1        pkgbuild_1.4.8        loo_2.8.0            
[43] tools_4.5.2           glue_1.8.0            grid_4.5.2           
[46] checkmate_2.3.3       generics_0.1.4        gtable_0.3.6         
[49] tzdb_0.5.0            data.table_1.17.8     hms_1.1.4            
[52] pillar_1.11.1         ggdist_3.3.3          posterior_1.6.1      
[55] splines_4.5.2         lattice_0.22-7        tidyselect_1.2.1     
[58] knitr_1.50            reformulas_0.4.2      arrayhelpers_1.1-0   
[61] gridExtra_2.3         V8_8.0.1              xfun_0.54            
[64] bridgesampling_1.2-1  matrixStats_1.5.0     stringi_1.8.7        
[67] VGAM_1.1-14           lazyeval_0.2.2        yaml_2.3.12          
[70] boot_1.3-32           evaluate_1.0.5        codetools_0.2-20     
[73] cli_3.6.5             RcppParallel_5.1.11-1 xtable_1.8-4         
[76] parameters_0.28.3     Rdpack_2.6.4          processx_3.8.6       
[79] globals_0.18.0        coda_0.19-4.1         svUnit_1.0.8         
[82] bdsmatrix_1.3-7       parallel_4.5.2        rstantools_2.5.0     
[85] bayestestR_0.17.0     bayesplot_1.14.0      Brobdingnag_1.2-9    
[88] listenv_0.10.0        mvtnorm_1.3-3         scales_1.4.0         
[91] insight_1.4.4         rlang_1.1.6           multcomp_1.4-29      </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>